spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: External
          uri: http://localhost:8085/
          predicates:
            - Path=/api/external/**
        - id: Internal
          uri: lb://SAMPLE-MS-1/
          predicates:
            - Path=/api/internal/** 
        - id: UserDetail
          uri: lb://USER-DETAIL/
          predicates:
            - Path=/api/User/** 
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level: 
    org:
      springframework:
        web: TRACE
