spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: External
          uri: http://localhost:8085/
          predicates:
            - Path=/api/external/**
        - id: Internal
          uri: http://localhost:8088/
          predicates:
            - Path=/api/internal/**
  config: 
    import: optional:configserver:http://localhost:8888
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level: 
    org:
      springframework:
        web: TRACE
